### ISSUE TITLE
Add a 'Register Wallet' page for use with CHAPI

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet-site#10]
Add a `https://lcw.app/register-wallet.html` page (the LCW PR https://github.com/digitalcredentials/learner-credential-wallet/pull/488 will interface with this page).
Model it after Gobekli's  https://gobekli.io/demo-credential-handler/ page, but obv change text/branding etc to LCW.

**Comment by kayaelle** [comment]
I think Atomic Jolt made need access to the repo.

**Comment by dmitrizagidulin** [comment]
> I think Atomic Jolt made need access to the repo.

Done, changed their permissions to write access.

**Comment by kezike** [comment]
@dmitrizagidulin In order for us to properly configure this functionality, we will need to statically host [these `.well-known` files](https://github.com/digitalcredentials/learner-credential-wallet-site/tree/main/.well-known). That will involve server-side configuration that I do not have the permission to perform. Could you either grant me that access or do it yourself (whichever is easier for you)?

**Comment by kayaelle** [comment]
@kezike - I'm going to change the status of this to In Progress.

**Comment by alexfigtree** [comment]
Tested on iOS. Also confirmed with @kezike that issue is completed.
