### ISSUE TITLE
Add favicon to lcw.app Site

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet-site#5]
Add a LCW folder favicon to lcw.app

**Comment by bmuramatsu** [comment]
yep!

**Comment by kayaelle** [comment]
@fields37 - can you follow up on this one?

**Comment by fields37** [comment]
I just added the favicon in here: https://github.com/digitalcredentials/learner-credential-wallet-site/commit/9a979b35a0032c50dab1aac7beb0ecd5b83acbb0

**Comment by kayaelle** [comment]
Thanks!
