### ISSUE TITLE
Change anchor  from #unsharepubliclink to #public-link-unshare

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet-site#9]
After publicly releasing LCW after the fix to https://github.com/digitalcredentials/learner-credential-wallet/issues/362

Remove `<a name="unsharepubliclink">` from line 58 of [faq.html](https://github.com/digitalcredentials/learner-credential-wallet-site/blob/main/faq.html). This is the "old" anchor name that should now be replaced in LCW.

How to test if fixed: If, after updating LCW and making this change, when a LCW user selects "What does this mean?" from the Credential Preview > Create Public Link > Unshare button (after a public link is created) > "Are you sure" modal they should go to the "I want to stop sharing a “Public Link”, how do I do so?" FAQ entry on https://lcw.app/faq.html.

**Comment by kayaelle** [comment]
See note in [https://github.com/digitalcredentials/learner-credential-wallet/issues/362](https://github.com/digitalcredentials/learner-credential-wallet/issues/362)

**Comment by jmcioffi4** [comment]
PR: https://github.com/digitalcredentials/learner-credential-wallet-site/pull/11
